### ISSUE TITLE
一度出品した商品の詳細を編集できる機能がほしい。

### ISSUE THREAD

**Issue by hashikuchi** [hashikuchi/freecycle#120]

**Comment by tagasouichiro** [comment]
商品の状態はどこで保持しているのか？

**Comment by hashikuchi** [comment]
> 商品の状態はどこで保持しているのか？
wp_postmeta テーブル内に、item_status というmeta_keyで保存されています。
add_post_meta, get_post_meta... といった操作用関数がWordPress標準で用意されています。

**Comment by tagasouichiro** [comment]
すみません、ありがとうございます！
