### ISSUE TITLE
ひとつの商品に複数のユーザから「ください」されると、未完了のnext actionができる

### ISSUE THREAD

**Issue by hashikuchi** [hashikuchi/freecycle#123]
再現手順:
1. ひとつの商品に複数のユーザから「ください」をする-> 「取引相手を確定してください」のtodoが複数ユーザの数ぶん発生する
2. 取引相手を確定する->「取引相手を確定してください」のtodoが完了せずに残る
3. 取引完了、評価まで終わらせる->「落札者を評価してください」のtodoが完了せずに残る

**Comment by tagasouichiro** [comment]
消去するTODOが毎回、１つのみになっていることが原因。
くださいされた人数が複数かどうかの判定をして、複数の場合その数だけTODO消去の動作を行えばよい

追記
くださいが承認されなかったユーザーに対して、承認されなかった旨を通知する必要がある
