### ISSUE TITLE
商品カテゴリ編集の際、親・子カテゴリを選択するとエラーがでる

### ISSUE THREAD

**Issue by tagasouichiro** [hashikuchi/freecycle#146]
子カテゴリのvalue="1"を設定しているので、Uncategorizedに入るはずが、、

**Comment by hashikuchi** [comment]
![2015-02-26 13 27 53](https://cloud.githubusercontent.com/assets/4316388/6383969/3dd228e0-bdbb-11e4-9a83-b8ec68b9e3c0.png)

親カテゴリ->南山大学、子カテゴリ->法学部 の商品に対し、編集ボタンを押して何も変えずに編集完了にしたら、親カテゴリがなくなって子カテゴリが南山大学になってしまいました。
