### ISSUE TITLE
マイページURLにユーザーログイン名が晒されている

### ISSUE THREAD

**Issue by tagasouichiro** [hashikuchi/freecycle#223]
・セキュリティ上よろしくないようです

**Comment by hashikuchi** [comment]
残念ながら、BuddyPress の仕様上URLの変更は厳しいみたいです。

>
you may be able to hide the element but you won’t be able to obscure the profile url so there’s really no way (at least that i know of) to make usernames truly private.
https://buddypress.org/support/topic/how-do-i-remove-username-from-buddypress-member-profiles/

6年も前から、
>「このプラグインならメアドでログインできるぜ！ユーザ名は不要だ！」
「……いや、メアドがURLに含まれるようになるからヤバイよ」
https://buddypress.org/support/topic/autogenerate-or-remove-username/

ってやりとりがあるくらいなので、対処は難しそう。

**Comment by tagasouichiro** [comment]
あっ、そうなんですね、、、
issue閉じときます。

**Comment by hashikuchi** [comment]
まーいくら仕様でもちょっとまずいよね〜…
いずれ改善されることに期待。
