### ISSUE TITLE
ログイントップページの本スライドにリンクを付ける

### ISSUE THREAD

**Issue by tagasouichiro** [hashikuchi/freecycle#225]

**Comment by TakenokoPro** [comment]
![snapcrab_noname_2015-8-9_2-26-51_no-00](https://cloud.githubusercontent.com/assets/9033882/9151466/382470c0-3e3e-11e5-8096-dc78ce4f5dea.png)
本棚っぽくしようと思い立ち実装しました。
本棚っぽく見せる画像の作成とデータベースに新たにテーブルを作成して参照するのが正しく本番環境で動くか確認が必要です。

**Comment by TakenokoPro** [comment]
![snapcrab_noname_2015-8-9_2-35-35_no-00](https://cloud.githubusercontent.com/assets/9033882/9151503/619d81e8-3e3f-11e5-9370-a7df71bf41e1.png)
ローカル環境では、phpMyAdminにて
操作→テーブル作成
名前:wp_book_link
カラム数:3
→(実行)

テーブルの構造は
post_id int型
image_src text型
update_time datetime型
で作成すれば良いと思います。

開発のメモとして記述しておきます。

**Comment by TakenokoPro** [comment]
![snapcrab_noname_2015-8-8_21-3-28_no-00](https://cloud.githubusercontent.com/assets/9033882/9151563/9d95b728-3e40-11e5-9e32-81c8a34d9019.png)
wp-contentの上階層にあるwp-includes内wp-db.phpファイルの中身も少し弄ります。
var $tables =array(...の最後に'book_link'を足します。

**Comment by TakenokoPro** [comment]
開発のメモとして記述しておきます。

**Comment by hashikuchi** [comment]
>wp-contentの上階層にあるwp-includes内wp-db.phpファイルの中身も少し弄ります。

おーっと、バージョン管理されていないファイルを触るのは極力さけてほしい！
それにwp-includesはWordPressそのものにひもづくから、WordPressのバージョン上げると変更が消えちゃうよ。

テーブル追加に関してですが、いまは以下のやり方で進めています。
1. テーブル名は wp_fmt_ で始める (fmt は freecycle meta table の意)
2. insert_timestamp, update_timestamp の2つのカラムを設ける。それぞれ timestamp 型
3.  plugins/freecycle/freecycle-meta-table の freecycle-meta-table.php ファイル内に、テーブル定義を記述する。また、fmt_active 関数内の $fmt_db_version 変数の値を上げる。これにより、開発環境構築時およびプラグインのアップデート時にテーブルが自動作成されるので。

あと、これってほんとにテーブル追加しないと実装できないのかな？理由を教えてもらえると助かります。

**Comment by TakenokoPro** [comment]
テーブルを新しく追加したい理由というのが、
https://github.com/hashikuchi/freecycle/blob/master/themes/freecycle/js/freecycleJS.php#L341
https://github.com/hashikuchi/freecycle/blob/master/plugins/freecycle/functions.php#L2909
functions.php に画像のURLを取得するための処理が書かれていますが、どうやらサムネイル画像形式の画像ファイルをランダムに15個取得してURLを返すという処理らしく、商品ページとの紐付けはありません。

商品ページのURL(アーカイブのID)を取得するには、存在するアーカイブIDを取得してからその商品ページで使用されている１枚目(検索した時に表示)の画像を探すという処理になると思います。

この場合、コード自体がややこしくなったり、「こんな本があります」と言いつつもあまり見かけない本が表示されてるのも微妙かなと思ったので、クリックされたのが最近の商品ページを30件程取得して、内10件をランダムに本棚に表示するとしたら、新学期・テスト前は教科書、フェア中はフェアの本のように表示される本棚が出来るのではと思ったわけです。

テーブル作成以外で、クリックの最終日時とアーカイブID、画像URLの紐づけが上手くいく方法があるなら、試してみたいのですが....
もう少し、練ってみます。

**Comment by hashikuchi** [comment]
>どうやらサムネイル画像形式の画像ファイルをランダムに15個取得してURLを返すという処理らしく、商品ページとの紐付けはありません。

最終的に生成されるJSONには画像のURLしか入ってませんが、それを生成する過程で商品ページを参照しているので、ひも付けは可能だと思います。

```
foreach ($rand_items->posts as $rand_item) {
		$arg = array(
                    // $rand_item は post オブジェクト
                    // IDプロパティから商品ページへのURLが生成できる
		    'post_parent' => $rand_item->ID,
		    'post_type'   => 'attachment',
		    'post_mime_type' => 'image',
		    'numberposts' => 1
		);
		$child = get_children($arg);
		//$childがとれたかどうかチェック
		$image = array_shift($child);
		if(!empty($image) && !empty($image->guid)){
                        // ここで商品ページのURLと画像のURLをひとつのオブジェクトに突っ込んでJSONエンコードすればJavaScript側でオブジェクトとして取ってこれるんじゃないかと予想
			array_push($image_urls, $image->guid);
		}
	}
```
$rand_items を取得する部分を、特定のカテゴリやクリック日時(←これどうやって取るかわからないけど)など、任意の条件に設定できるようにすれば、フェアとの連動もできるようになるかと思います。

その場合は、themes/freecycle/templates 以下のファイルを編集して、
ダッシュボードの 設定->テクスチェンジ のメニューを追加することになります。

その他、WordPressのオブジェクトについてはドキュメントを参照してみてください。
http://wpdocs.osdn.jp/Main_Page
