### ISSUE TITLE
商品検索の改善

### ISSUE THREAD

**Issue by tagasouichiro** [hashikuchi/freecycle#312]
文字列検索がうまく機能していないとの指摘のため(未調査)

**Comment by tagasouichiro** [comment]
#311 
に関連して、冊数が0の商品を検索結果に含めない処理も必要

**Comment by yugogura** [comment]
運営さんに、詳しい情報をもらう
いつ、どんな言葉で調べたら、どんな結果が返ってくるか。

**Comment by yugogura** [comment]
おそらく、古い出品リンクが目立たないだけ
