### ISSUE TITLE
取引場所の指定を地図を表示することで簡略化

### ISSUE THREAD

**Issue by tagasouichiro** [hashikuchi/freecycle#96]
目的
・安全な場所での交換によるトラブルを予防

**Comment by hashikuchi** [comment]
各大学・学部の緯度経度をデータとして登録し、ユーザのデータから呼び出すようにしたほうがよさそう。

**Comment by hashikuchi** [comment]
地図指定機能の課題
・初期表示の地図を設定できるようにする必要あり。設定されていない場合は運営側の設定した初期地図が表示される。+ 初期設定を促すメッセージを出す
・場所検索フォームを用意する->ドロップダウンリストで指定できるようにする。管理画面に設定フォームを追加「その他」は無し。
・APIキーを管理者画面で設定できるようにする
・メッセージ欄は残す。
